import { logger } from '../../lib/default-logger';
import {
  california,
  chateauGreen,
  kepple,
  neonBlue,
  nevada,
  redOrange,
  royalBlue,
  shakespeare,
  stormGrey,
  tomatoOrange,
} from './colors';
import type { ColorMode, ColorSystemOptions, PaletteRange, PrimaryColor } from './types';

const primarySchemes: Record<PrimaryColor, Record<ColorMode, PaletteRange>> = {
  chateauGreen: {
    dark: {
      ...chateauGreen,
      light: chateauGreen[300],
      main: chateauGreen[400],
      dark: chateauGreen[500],
      contrastText: 'var(--chakra-colors-black)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
    light: {
      ...chateauGreen,
      light: chateauGreen[400],
      main: chateauGreen[500],
      dark: chateauGreen[600],
      contrastText: 'var(--chakra-colors-white)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
  },
  neonBlue: {
    dark: {
      ...neonBlue,
      light: neonBlue[300],
      main: neonBlue[400],
      dark: neonBlue[500],
      contrastText: 'var(--chakra-colors-black)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
    light: {
      ...neonBlue,
      light: neonBlue[400],
      main: neonBlue[500],
      dark: neonBlue[600],
      contrastText: 'var(--chakra-colors-white)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
  },
  royalBlue: {
    dark: {
      ...royalBlue,
      light: royalBlue[300],
      main: royalBlue[400],
      dark: royalBlue[500],
      contrastText: 'var(--chakra-colors-black)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
    light: {
      ...royalBlue,
      light: royalBlue[400],
      main: royalBlue[500],
      dark: royalBlue[600],
      contrastText: 'var(--chakra-colors-white)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
  },
  tomatoOrange: {
    dark: {
      ...tomatoOrange,
      light: tomatoOrange[300],
      main: tomatoOrange[400],
      dark: tomatoOrange[500],
      contrastText: 'var(--chakra-colors-black)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
    light: {
      ...tomatoOrange,
      light: tomatoOrange[400],
      main: tomatoOrange[500],
      dark: tomatoOrange[600],
      contrastText: 'var(--chakra-colors-white)',
      activated: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-activatedOpacity))',
      hovered: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-hoverOpacity))',
      selected: 'rgba(var(--chakra-colors-primary) / var(--chakra-colors-action-selectedOpacity))',
    },
  },
};

interface Config {
  primaryColor: PrimaryColor;
}

export function colorSchemes(config: Config): Partial<Record<ColorMode, ColorSystemOptions>> {
  let primary = primarySchemes[config.primaryColor];

  if (!primary) {
    logger.warn(`No primary color found for ${config.primaryColor}. Using neonBlue instead.`);
    primary = primarySchemes.neonBlue;
  }

  return {
    dark: {
      palette: {
        action: {
          disabled: 'var(--chakra-colors-gray-300)',
          disabledBackground: 'rgba(0, 0, 0, 0.12)',
          activatedOpacity: '0.12',
          hoverOpacity: '0.08',
          selectedOpacity: '0.16',
        },
        background: {
          default: 'var(--chakra-colors-gray-950)',
          defaultChannel: '9 10 11',
          paper: 'var(--chakra-colors-gray-900)',
          level1: 'var(--chakra-colors-gray-800)',
          level2: 'var(--chakra-colors-gray-700)',
          level3: 'var(--chakra-colors-gray-600)',
        },
        common: { black: '#000000', white: '#ffffff' },
        divider: 'var(--chakra-colors-gray-700)',
        dividerChannel: '50 56 62',
        error: {
          ...redOrange,
          light: redOrange[300],
          main: redOrange[400],
          dark: redOrange[500],
          contrastText: 'var(--chakra-colors-black)',
          activated: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-selectedOpacity))',
        },
        info: {
          ...shakespeare,
          light: shakespeare[300],
          main: shakespeare[400],
          dark: shakespeare[500],
          contrastText: 'var(--chakra-colors-black)',
          activated: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-selectedOpacity))',
        },
        neutral: { ...nevada },
        primary: primary.dark,
        secondary: {
          ...nevada,
          light: nevada[100],
          main: nevada[200],
          dark: nevada[300],
          contrastText: 'var(--chakra-colors-black)',
          activated: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-selectedOpacity))',
        },
        success: {
          ...kepple,
          light: kepple[300],
          main: kepple[400],
          dark: kepple[500],
          contrastText: 'var(--chakra-colors-black)',
          activated: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-selectedOpacity))',
        },
        text: {
          primary: 'var(--chakra-colors-gray-100)',
          primaryChannel: '240 244 248',
          secondary: 'var(--chakra-colors-gray-400)',
          secondaryChannel: '159 166 173',
          disabled: 'var(--chakra-colors-gray-600)',
        },
        warning: {
          ...california,
          light: california[300],
          main: california[400],
          dark: california[500],
          contrastText: 'var(--chakra-colors-black)',
          activated: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-selectedOpacity))',
        },
        Avatar: { defaultBg: 'var(--chakra-colors-gray-200)' },
        Backdrop: { bg: 'rgba(0, 0, 0, 0.5)' },
        OutlinedInput: { border: 'var(--chakra-colors-gray-700)' },
        TableCell: { border: 'var(--chakra-colors-divider)' },
        Tooltip: { bg: 'rgba(10, 13, 20, 0.75)' },
      },
    },
    light: {
      palette: {
        action: {
          disabledBackground: 'rgba(0, 0, 0, 0.06)',
          activatedOpacity: '0.12',
          hoverOpacity: '0.08',
          selectedOpacity: '0.16',
        },
        background: {
          default: 'var(--chakra-colors-white)',
          defaultChannel: '255 255 255',
          paper: 'var(--chakra-colors-white)',
          level1: 'var(--chakra-colors-gray-50)',
          level2: 'var(--chakra-colors-gray-100)',
          level3: 'var(--chakra-colors-gray-200)',
        },
        common: { black: '#000000', white: '#ffffff' },
        divider: 'var(--chakra-colors-gray-200)',
        dividerChannel: '220 223 228',
        error: {
          ...redOrange,
          light: redOrange[400],
          main: redOrange[500],
          dark: redOrange[600],
          contrastText: 'var(--chakra-colors-white)',
          activated: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-error) / var(--chakra-colors-action-selectedOpacity))',
        },
        info: {
          ...shakespeare,
          light: shakespeare[400],
          main: shakespeare[500],
          dark: shakespeare[600],
          contrastText: 'var(--chakra-colors-white)',
          activated: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-info) / var(--chakra-colors-action-selectedOpacity))',
        },
        neutral: { ...stormGrey },
        primary: primary.light,
        secondary: {
          ...nevada,
          light: nevada[600],
          main: nevada[700],
          dark: nevada[800],
          contrastText: 'var(--chakra-colors-white)',
          activated: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-secondary) / var(--chakra-colors-action-selectedOpacity))',
        },
        success: {
          ...kepple,
          light: kepple[400],
          main: kepple[500],
          dark: kepple[600],
          contrastText: 'var(--chakra-colors-white)',
          activated: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-success) / var(--chakra-colors-action-selectedOpacity))',
        },
        text: {
          primary: 'var(--chakra-colors-gray-900)',
          primaryChannel: '33 38 54',
          secondary: 'var(--chakra-colors-gray-500)',
          secondaryChannel: '102 112 133',
          disabled: 'var(--chakra-colors-gray-400)',
        },
        warning: {
          ...california,
          light: california[400],
          main: california[500],
          dark: california[600],
          contrastText: 'var(--chakra-colors-white)',
          activated: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-activatedOpacity))',
          hovered: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-hoverOpacity))',
          selected: 'rgba(var(--chakra-colors-warning) / var(--chakra-colors-action-selectedOpacity))',
        },
        Avatar: { defaultBg: 'var(--chakra-colors-gray-600)' },
        Backdrop: { bg: 'rgb(18, 22, 33, 0.8)' },
        OutlinedInput: { border: 'var(--chakra-colors-gray-200)' },
        TableCell: { border: 'var(--chakra-colors-divider)' },
        Tooltip: { bg: 'rgba(10, 13, 20, 0.75)' },
      },
    },
  };
}
